### ISSUE TITLE
Add support for Disallowed Comment Keys

### ISSUE THREAD

**Issue by danielmilner** [firetreedesign/hey-notify#58]
Notifications should not be sent when they match any of the Disallowed Comment Keys defined under Settings > Discussion in the WordPress Admin.

We are already ignoring Spam comments, maybe it's as easy as also checking for Trash comments. If not, we can use the [wp_check_comment_disallowed_list()](https://developer.wordpress.org/reference/functions/wp_check_comment_disallowed_list/) function.

https://wordpress.org/support/topic/filter-comments-event-type/

**Comment by zedpelin** [comment]
Hey @danielmilner, I've created  #59 that will resolve #58. I believe I have not correctly linked the PR with this issue, sorry about that.

**Comment by danielmilner** [comment]
Thanks @zedpelin, I'll take a look at this soon.
